---

  - name: tomcat binary download
    get_url:
      url: "{{ tomcat_binary_url }}"
      dest: "{{ tomcat_dest }}{{ tomcat_binary }}"

  - name: extract archive
    unarchive:
      src: "{{ tomcat_dest }}{{ tomcat_binary }}"
      dest: "{{ tomcat_dest }}"
      remote_src: yes
      owner: "{{ tomcat_os_user_name }}"
      group: "{{ tomcat_os_group_name }}"

  - name: symlink install directory
    file:
      src: "{{ tomcat_dest }}{{ tomcat_target_dir }}"
      path: "{{ tomcat_dest }}{{ tomcat_symlink }}"
      state: link