---

- name: create server configuration
  template:
    src: server.xml.j2
    dest: "{{ tomcat_conf_dir }}/server.xml"
  notify: tomcat restart

- name: create web configuration
  template:
    src: web.xml.j2
    dest: "{{ tomcat_conf_dir }}/web.xml"
  notify: tomcat restart

- name: restart tomcat
  service:
    name: "{{tomcat_service_name}}"
    state: restarted
    enabled: yes

- name: wait for tomcat to start
  wait_for:
    port: "{{http_port}}"
