---

- name: Install Java 1.8
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: tomcat group add
  group:
    name: "{{ tomcat_os_group_name }}"

- name: tomcat user add
  user:
    name: "{{ tomcat_os_user_name }}"
    group: "{{ tomcat_os_group_name }}"
    home: "{{ tomcat_home_path }}"
    createhome: no
